## Config map to insert a landing index.html page in the docker.  This may be removed later if the same is done while building the docker.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-index
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <style>
    .content {
      max-width: 700px;
      margin: auto;
      text-align: center;
    }
    </style>
    <body>
      <div class="content">
        <img src="https://mosip.github.io/mosip-helm/mosip_logo.png">
        <h2 style="font-family:verdana;"> Registration Client</h2>
        <a href="https://{{ .Values.istio.host }}/registration-client/{{ .Values.regclient.version  }}/reg-client.zip" style="font-family:verdana;">Windows 10</a>
        <h4 style="font-family:verdana;"> Registration Client Test Utility</h2>
        <a href="https://{{ .Values.istio.host }}/registration-client/{{ .Values.regclient.version  }}/registration-test-utility.zip" style="font-family:verdana;">Windows 10</a>
      </div>
    </body>
    </html>
